version: '3'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    labels:
      traefik.http.services.minio.loadbalancer.server.port: 9001
      traefik.http.routers.minio.rule: 'Host(`${MINIO_DOMAIN}`)'
      traefik.http.routers.minio.tls: 'false'
      traefik.http.routers.minio.tls.certresolver: 'default'
      traefik.enable: 'true'
volumes:
  minio-data:
    driver: local
  minio-config:
    driver: local

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
