version: '3'
x-minio-common: &minio-common
  restart: always
  # see https://github.com/minio/minio/tags 
  # and https://hub.docker.com/r/minio/minio/tags
  image: minio/minio:RELEASE.2022-05-19T18-20-59Z
  command: server --console-address ":9001" ${MINIO_SCALE_PATTERN}
  ports:
    - '9001:9001'
  environment:
    MINIO_ROOT_USER:
    MINIO_ROOT_PASSWORD:

services:
  minio1:
    <<: *minio-common
    volumes:
      - ./data/minio1:/data
    labels:
      traefik.http.routers.minio1.rule: 'Host(`${MINIO_DOMAIN}`)'
      traefik.http.routers.minio1.tls: 'false'
      traefik.http.routers.minio1.tls.certresolver: 'default'
      traefik.http.routers.minio1.service: minio1
      traefik.http.services.minio1.loadbalancer.server.port: 9000
      traefik.http.services.minio1.loadbalancer.server.scheme: http
      traefik.enable: 'true'
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
