version: '3'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./data/etcd:/bitnami/etcd
  minio1:
    environment:
      MINIO_ETCD_ENDPOINTS: http://etcd:2379
