version: '3'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd:/bitnami/etcd
  minio1:
    environment:
      MINIO_ETCD_ENDPOINTS: http://etcd:2379

volumes:
  etcd:
